### ISSUE TITLE
Error Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by stereo3d** [piste2750/homebrew-ltfs#1]
thank you for your work!

I tried to install ltfs following your instruction BIGSUR mac min M1 silicon.
However, it seems the architecture is not supported.
Please help!! Many thanks.

I attach the end of the output after make:
[bigsur_m1_error.txt](https://github.com/piste2750/homebrew-ltfs/files/6029791/bigsur_m1_error.txt)

**Comment by stereo3d** [comment]
Tried with the latest version of Fuse 4.1.0 for Apple M1 silicon.
It does not seem to be recognized by the brew formulae. 

Unfortunately still same error:
Undefined symbols for architecture arm64:
  "_bin_mkltfs_dat", referenced from:
      _main in mkltfs-mkltfs.o
ld: symbol(s) not found for architecture arm64

thank you for every possible help

[terminal.txt](https://github.com/piste2750/homebrew-ltfs/files/6173496/terminal.txt)

**Comment by stereo3d** [comment]
I tried again, following your instructions
Mac Mini M1 - OS 11.2.3 - XCode 12.4

Downloaded macFuse dmg 4.1.0 for Apple M1 silicon.

`brew install ltfs

returns 

`Error: ltfs: Unsupported special dependency :osxfuse`

could there be some confusion between macfuse and osxfuse?

Any help greatly appreciated.

**Comment by piste2750** [comment]
Dup of #3. 

I hope it would be fixed into 652ea4d744852ce6c842e48c9b0ec24e555f4d51.
